# Generated by Django 3.2.6 on 2021-10-28 21:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this country', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a country name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this person', primary_key=True, serialize=False)),
                ('fullname', models.CharField(help_text='Enter a player fullname', max_length=30)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.country')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this rank', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a rank name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.person')),
                ('nick', models.CharField(help_text='Enter a player nick', max_length=25)),
                ('played_hours', models.IntegerField()),
            ],
            bases=('players.person',),
        ),
    ]
