# Generated by Django 3.2.6 on 2021-11-26 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this map', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a map name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this setup', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a rol name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this setting', primary_key=True, serialize=False)),
                ('sensivility', models.FloatField(help_text='Enter a sens number')),
                ('dpi', models.IntegerField(help_text='Enter a dpi number')),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this setup', primary_key=True, serialize=False)),
                ('monitor', models.CharField(help_text='Enter a monitor name', max_length=25)),
                ('mouse', models.CharField(help_text='Enter a mouse name', max_length=25)),
                ('mousepad', models.CharField(help_text='Enter a mousepad name', max_length=25)),
                ('keyboard', models.CharField(help_text='Enter a keyboard name', max_length=25)),
                ('headset', models.CharField(help_text='Enter a headset name', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this setup', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a agent name', max_length=20)),
                ('rol', models.ForeignKey(help_text='Select a rol for this Agent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.rol')),
            ],
        ),
    ]
