# Generated by Django 3.2.6 on 2021-11-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_agent_map_rol_setting_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='agents_pool',
            field=models.ManyToManyField(help_text='Select a agents to make agents_pool', to='players.Agent'),
        ),
    ]
