# Generated by Django 3.2.6 on 2021-11-26 21:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20211126_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='agents_pool',
        ),
        migrations.AddField(
            model_name='player',
            name='setup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.setup'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this person', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='setup',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a name for this setup', max_length=50, null=True),
        ),
    ]
