# Generated by Django 3.2.6 on 2021-11-26 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20211126_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.setting'),
        ),
        migrations.AddField(
            model_name='setting',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a setting name', max_length=25, null=True),
        ),
    ]
