# Generated by Django 3.2.6 on 2021-11-27 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20211126_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='player',
            name='setup',
        ),
        migrations.AddField(
            model_name='player',
            name='dpi',
            field=models.IntegerField(blank=True, help_text='Enter a dpi number', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='headset',
            field=models.CharField(blank=True, help_text='Enter a headset name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='keyboard',
            field=models.CharField(blank=True, help_text='Enter a keyboard name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='monitor',
            field=models.CharField(blank=True, help_text='Enter a monitor name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='mouse',
            field=models.CharField(blank=True, help_text='Enter a mouse name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='mousepad',
            field=models.CharField(blank=True, help_text='Enter a mousepad name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='sensivility',
            field=models.FloatField(blank=True, help_text='Enter a sens number', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.rank'),
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.DeleteModel(
            name='Setup',
        ),
    ]
