# Generated by Django 3.2.6 on 2021-12-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_map_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='tierA',
            field=models.ManyToManyField(blank=True, help_text='Enter a tier A agent', related_name='agent_tierA', to='players.Agent'),
        ),
        migrations.AlterField(
            model_name='map',
            name='tierS',
            field=models.ManyToManyField(blank=True, help_text='Enter a tier S agent', related_name='agent_tierS', to='players.Agent'),
        ),
    ]
