# Generated by Django 3.2.6 on 2021-12-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20211202_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='tierB',
            field=models.ManyToManyField(blank=True, help_text='Enter a tier B agent', related_name='agent_tierB', to='players.Agent'),
        ),
        migrations.AddField(
            model_name='map',
            name='tierC',
            field=models.ManyToManyField(blank=True, help_text='Enter a tier C agent', related_name='agent_tierC', to='players.Agent'),
        ),
        migrations.AddField(
            model_name='map',
            name='tierD',
            field=models.ManyToManyField(blank=True, help_text='Enter a tier D agent', related_name='agent_tierD', to='players.Agent'),
        ),
    ]
