# Generated by Django 3.2.6 on 2021-12-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_auto_20211202_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='map',
            name='minimapa',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
