# Generated by Django 3.2.6 on 2021-12-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_auto_20211202_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='players')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, upload_to='players'),
        ),
        migrations.AlterField(
            model_name='map',
            name='minimapa',
            field=models.ImageField(blank=True, upload_to='players'),
        ),
    ]
