# Generated by Django 3.2.6 on 2021-12-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_auto_20211203_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
