# Generated by Django 3.2.6 on 2021-12-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_agent_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(blank=True, help_text='Enter a person description', max_length=5000, null=True),
        ),
    ]
