# Generated by Django 3.2.6 on 2021-12-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_person_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
