# Generated by Django 3.2.6 on 2021-12-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.CharField(blank=True, help_text='Enter a map description', max_length=6000),
        ),
        migrations.AddField(
            model_name='rank',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
