# Generated by Django 3.2.6 on 2021-12-06 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_auto_20211204_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='tierA',
        ),
        migrations.RemoveField(
            model_name='map',
            name='tierB',
        ),
        migrations.RemoveField(
            model_name='map',
            name='tierC',
        ),
        migrations.RemoveField(
            model_name='map',
            name='tierD',
        ),
        migrations.RemoveField(
            model_name='map',
            name='tierS',
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this setup', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a name tier', max_length=20)),
                ('agents', models.ManyToManyField(blank=True, help_text='Enter a tier agent', to='players.Agent')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='tier_list',
            field=models.ManyToManyField(blank=True, help_text='Enter a tier', related_name='tier', to='players.Tier'),
        ),
    ]
